---
title: What Stages are Being Diagnosed in Each Intervention Scenario
author: Christian Testa
date: July 15, 2019
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
devtools::load_all()
library(dplyr)
library(magrittr)
library(ggplot2)
library(tidyr)
library(here)
theme_set(theme_bw())
```


```{r def breakdown_diagnoses}
#' Breakdown Diagnoses into Stages
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_diagnoses_by_stage <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,
		popsize = rowSums(sol[intervention_period, allpop.index]),
		# year = sol[intervention_period, 1],
		diagnosed_primary = rowSums(sol[intervention_period, 1 + d1.index])   
		- rowSums(sol[intervention_period-52, 1 + d1.index]),
		diagnosed_secondary = rowSums(sol[intervention_period, 1 + d2.index]) 
		- rowSums(sol[intervention_period-52, 1 + d2.index]),
		diagnosed_early_latent = rowSums(sol[intervention_period, 1 + d3.index]) 
		- rowSums(sol[intervention_period-52, 1 + d3.index]),
		diagnosed_late_latent = rowSums(sol[intervention_period, 1 + d4.index]) 
		- rowSums(sol[intervention_period-52, 1 + d4.index])
		) %>% 
	mutate(diagnosed_primary = diagnosed_primary / popsize * 100000, 
		diagnosed_secondary = diagnosed_secondary / popsize * 100000, 
		diagnosed_early_latent = diagnosed_early_latent / popsize * 100000, 
		diagnosed_late_latent = diagnosed_late_latent / popsize * 100000 
	) %>% 
	select(-popsize) %>% 
	gather(stage, diagnoses, -year) %>% 
	mutate(stage = gsub("diagnosed_", "", stage)) %>% 
	as.data.frame() 
}


#' Breakdown Incidence by Reinfection Status
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_incidence_by_reinfection <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,
		popsize = rowSums(sol[intervention_period, 1 + allpop.index]),
		incidence_first_time = rowSums(sol[intervention_period,1 +  inc.index]) - rowSums(sol[intervention_period-52, 1 + inc.index]),
		incidence_reinfection = rowSums(sol[intervention_period,1 +  incr.index]) - rowSums(sol[intervention_period-52, 1 + incr.index])
		) %>% 
	mutate(incidence_first_time = incidence_first_time / popsize * 100000, 
		incidence_reinfection = incidence_reinfection / popsize * 100000 
	) %>% 
	select(-popsize) %>% 
	gather(stage, infections, -year) %>% 
	as.data.frame() 
}


#' Breakdown Prevalence into Stages
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_prevalence_by_stage <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,
		popsize = rowSums(sol[intervention_period, 1 + allpop.index]),
		# year = sol[intervention_period, 1],
		primary = rowSums(sol[intervention_period, 1 + c(prim.index, primr.index)]),
		secondary = rowSums(sol[intervention_period, 1 + c(sec.index, secr.index)]),
		early_latent = rowSums(sol[intervention_period, 1 + c(early.index, earlyr.index)]),
		late_latent = rowSums(sol[intervention_period, 1 + c(latent.index, latentr.index)])
		) %>% 
	mutate(primary = primary / popsize * 100000, 
		secondary = secondary / popsize * 100000, 
		early_latent = early_latent / popsize * 100000, 
		late_latent = late_latent / popsize * 100000) %>% 
	select(-popsize) %>% 
	gather(stage, diagnoses, -year) %>% 
	as.data.frame() 
}

```


# break down diagnoses by stage

```{r def simulate_interventions}

simulate_interventions <- function(theta, info_extractor) {
	intervention_outcomes <- list()
<<<<<<< HEAD
	for (intervention in c('basecase', 'annual', 'msm_annual',
												 'msm_annual_hr_msm_quarterly', 'msm_8x_yearly',
												 'prior_diagnosis_quarterly', 'high_activity_annual',
												 'high_activity_twice_annual',
												 'msm_annual_all_hr_half_annual'
												 )) {
=======
	for (intervention in c('basecase', 'annual', 'msm_annual', 'msm_annual_hr_msm_quarterly', 'prior_diagnosis_quarterly', 'msm_8x_annually')) {
>>>>>>> 1d4a8332b3a8d7fd686579c4f8f4112dac677c54
		e <- constructSimulationEnvironment(theta)
		e$params$output_weekly <- TRUE
		modify_simulation_environment_for_an_intervention(e, intervention)
		runSimulation(e)
		intervention_outcomes[[length(intervention_outcomes)+1]] <- 
			cbind.data.frame(intervention = intervention, info_extractor(e$sim$out))
	}
	do.call(rbind.data.frame, intervention_outcomes)
}
```

```{r compute diagnoses data}

for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_diagnoses_by_stage))
}

df1 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))
```



```{r plotting code, fig.width = 8, fig.height = 8}
p1 <- ggplot(filter(df1, state == 'Louisiana'), aes(x = year, y = diagnoses, fill = stage)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Greens") + 
	xlab("Diagnoses per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	ggtitle("Diagnoses per 100,000 per Year by Disease Stage", subtitle = 'Louisiana')

ggsave(plot = p1, filename = "diagnoses_la.png", height = unit(5, 'in'), width = unit(10, 'in'))


p2 <- ggplot(filter(df1, state == 'Massachusetts'), aes(x = year, y = diagnoses, fill = stage)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Greens") + 
	xlab("Diagnoses per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	ggtitle("Diagnoses per 100,000 per Year by Disease Stage", subtitle = 'Massachusetts') 

ggsave(plot = p2, filename = "diagnoses_ma.png", height = unit(5, 'in'), width = unit(10, 'in'))
```



# Prevalence 


```{r compute prevalence data}

for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_prevalence_by_stage))
}

df2 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))
```



```{r plotting code 2, fig.height = 8, fig.width = 8}

p3 <- ggplot(filter(df2, state == 'Louisiana'), aes(x = year, y = diagnoses, fill = stage)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Reds") + 
	xlab("Prevalent Infections") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	ggtitle("Prevalent Infections per 100,000 by Disease Stage", subtitle = 'Louisiana') 

ggsave(plot = p3, filename = 'prevalent_infections_by_stage_la.png', width = unit(10, 'in'), height = unit(5, 'in'))

p4 <- ggplot(filter(df2, state == 'Massachusetts'), aes(x = year, y = diagnoses, fill = stage)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Reds") + 
	xlab("Prevalent Infections") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	ggtitle("Prevalent Infections per 100,000 by Disease Stage", subtitle = 'Massachusetts')

ggsave(plot = p4, filename = 'prevalent_infections_by_stage_ma.png', width = unit(10, 'in'), height = unit(5, 'in'))
```


```{r incidence}
for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_incidence_by_reinfection))
}

df3 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))


p5 <- ggplot(filter(df3, state == 'Louisiana'), aes(x = year, y = infections, fill = stage)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Blues") + 
	xlab("Incident Infections Per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'reinfection status') + 
	ggtitle("Incident Infections per 100,000 per Year by Reinfection Status (Past 2 Years)", subtitle = 'Louisiana') 

ggsave(plot = p5, filename = 'incident_infections_la.png', width = unit(10, 'in'), height = unit(5, 'in'))

p6 <- ggplot(filter(df3, state == 'Massachusetts'), aes(x = year, y = infections, fill = stage)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Blues") + 
	xlab("Incident Infections Per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'reinfection status') + 
	ggtitle("Incident Infections per 100,000 per Year by Reinfection Status (Past 2 Years)", subtitle = 'Massachusetts') 

ggsave(plot = p6, filename = 'incident_infections_ma.png', width = unit(10, 'in'), height = unit(5, 'in'))
```




```{r}
library(cowplot)
plot_grid(p1, p3, p5, p2, p4, p6)
ggsave("2x3_diagnoses_and_prevalent_infections.png", width = unit(30, 'in'), height = unit(15, 'in'))
```



```{r incidence by gender group}

#' Breakdown Incidence by Sex
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_incidence_by_sex <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,
		popsize = rowSums(sol[intervention_period, allpop.index]),

		msw = rowSums(sol[intervention_period, 1 + c(inc.index[msw], incr.index[msw])])
			- rowSums(sol[intervention_period-52,1 +  c(inc.index[msw], incr.index[msw])]),

		msm = rowSums(sol[intervention_period, 1 + c(inc.index[msm], incr.index[msm])]) 
		  - rowSums(sol[intervention_period-52, 1 + c(inc.index[msm], incr.index[msm])]),

		w = rowSums(sol[intervention_period, 1 + c(inc.index[females], incr.index[females])]) 
			- rowSums(sol[intervention_period-52,1 +  c(inc.index[females], incr.index[females])])
		) %>% 
	mutate(msw = msw / popsize * 100000, 
		msm = msm / popsize * 100000,
		w = w / popsize * 100000
	) %>% 
	select(-popsize) %>% 
	gather(sex, infections, -year) %>% 
	as.data.frame() 
}



for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_incidence_by_sex))
}


df4 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))


p7 <- ggplot(filter(df4, state == 'Louisiana'), aes(x = year, y = infections, fill = sex)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Purples") + 
	xlab("Incident Infections Per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Incident Infections per 100,000 per Year by Sex", subtitle = 'Louisiana') 

ggsave(plot = p7, filename = 'incident_infections_by_sex_la.png', width = unit(10, 'in'), height = unit(5, 'in'))

p8 <- ggplot(filter(df4, state == 'Massachusetts'), aes(x = year, y = infections, fill = sex)) + 
	geom_area(colour="black", size=.2, alpha=.4) + 
	scale_fill_brewer(palette="Purples") + 
	xlab("Incident Infections Per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Incident Infections per 100,000 per Year by Sex", subtitle = 'Massachusetts') 

ggsave(plot = p8, filename = 'incident_infections_by_sex_ma.png', width = unit(10, 'in'), height = unit(5, 'in'))


library(cowplot)
plot_grid(p1, p3, p5, p7, p2, p4, p6, p8, nrow = 2)
ggsave("2x4_diagnoses_and_prevalent_infections.png", width = unit(35, 'in'), height = unit(15, 'in'))
```


```{r}

#' Breakdown Incidence by Reinfection Status
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_msm_incidence_by_risk <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	msm_low <- pop[pop$k == 'low' & grepl('msm', pop$i), 'index']
	msm_high <- pop[pop$k == 'high' & grepl('msm', pop$i), 'index']

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,
		popsize_low = rowSums(sol[intervention_period, 1 + 
													c(s.index[msm_low], sr.index[msm_low],
														e.index[msm_low], er.index[msm_low],
														prim.index[msm_low], primr.index[msm_low],
														sec.index[msm_low], secr.index[msm_low],
														early.index[msm_low], earlyr.index[msm_low], 
														latent.index[msm_low], latentr.index[msm_low])]),
		popsize_high = rowSums(sol[intervention_period, 1 + 
													c(s.index[msm_high], sr.index[msm_high],
														e.index[msm_high], er.index[msm_high],
														prim.index[msm_high], primr.index[msm_high],
														sec.index[msm_high], secr.index[msm_high],
														early.index[msm_high], earlyr.index[msm_high], 
														latent.index[msm_high], latentr.index[msm_high])]),

		msm_low = rowSums(sol[intervention_period, 1 + c(inc.index[msm_low], incr.index[msm_low])]) 
		  - rowSums(sol[intervention_period-52, 1 + c(inc.index[msm_low], incr.index[msm_low])]),

		msm_high = rowSums(sol[intervention_period, 1 + c(inc.index[msm_high], incr.index[msm_high])]) 
			- rowSums(sol[intervention_period-52, 1 + c(inc.index[msm_high], incr.index[msm_high])])
		) %>% 
	mutate(msm_low = msm_low / popsize_low * 100, 
		msm_high = msm_high / popsize_high * 100
	) %>% 
	select(-popsize_low, -popsize_high) %>% 
	gather(risk, infections, -year) %>% 
	as.data.frame() 
}



for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_msm_incidence_by_risk))
}

df5 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))

p9 <- ggplot(filter(df5, state == 'Louisiana'), aes(x = year, y = infections, color = risk)) + 
	geom_line(size = 1.5) + 
	# scale_color_brewer(palette="Purples") + 
	ylab("Incident Infections Per Year") + 
	facet_wrap(~ intervention) + 
	xlab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Incidence Rate in MSM Infections per 100 per Year by Risk", subtitle = 'Louisiana') 

ggsave(plot = p9, filename = 'incidence_msm_by_risk_la.png', width = unit(10, 'in'), height = unit(5, 'in'))

# p10 <- ggplot(filter(df5, state == 'Massachusetts'), aes(x = year, y = infections, fill = sex)) + 
# 	geom_area(colour="black", size=.2, alpha=.4) + 
# 	scale_fill_brewer(palette="Purples") + 
# 	xlab("Incident Infections Per Year") + 
# 	facet_wrap(~ intervention) + 
# 	ylab("Year") + 
# 	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
# 	theme(axis.text.x = element_text(angle = 90)) + 
# 	labs(fill = 'sex') + 
# 	ggtitle("Incident Infections per 100,000 per Year by Sex", subtitle = 'Massachusetts') 

p10 <- ggplot(filter(df5, state == 'Massachusetts'), aes(x = year, y = infections, color = risk)) + 
	geom_line() + 
	# scale_color_brewer(palette="Purples") + 
	xlab("Incident Infections Per Year") + 
	facet_wrap(~ intervention) + 
	ylab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Incidence Rate in MSM Infections per 100 per Year by Risk", subtitle = 'Massachusetts') 



ggsave(plot = p10, filename = 'incidence_msm_by_risk_ma.png', width = unit(10, 'in'), height = unit(5, 'in'))

```


```{r}

#' Breakdown Prevalence by Risk Status in MSM
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_msm_prevalence_by_risk <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	msm_low <- pop[pop$k == 'low' & grepl('msm', pop$i), 'index']
	msm_high <- pop[pop$k == 'high' & grepl('msm', pop$i), 'index']

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,

		popsize_low = rowSums(sol[intervention_period, 1 + 
													c(s.index[msm_low], sr.index[msm_low],
														e.index[msm_low], er.index[msm_low],
														prim.index[msm_low], primr.index[msm_low],
														sec.index[msm_low], secr.index[msm_low],
														early.index[msm_low], earlyr.index[msm_low], 
														latent.index[msm_low], latentr.index[msm_low])]),

		popsize_high = rowSums(sol[intervention_period, 1 + 
													c(s.index[msm_high], sr.index[msm_high],
														e.index[msm_high], er.index[msm_high],
														prim.index[msm_high], primr.index[msm_high],
														sec.index[msm_high], secr.index[msm_high],
														early.index[msm_high], earlyr.index[msm_high], 
														latent.index[msm_high], latentr.index[msm_high])]),

		msm_low = rowSums(sol[intervention_period, 1 + 
											c(e.index[msm_low], er.index[msm_low],
												prim.index[msm_low], primr.index[msm_low],
												sec.index[msm_low], secr.index[msm_low],
												early.index[msm_low], earlyr.index[msm_low],
												latent.index[msm_low], latentr.index[msm_low])]),

		msm_high = rowSums(sol[intervention_period, 1 + 
											c(e.index[msm_high], er.index[msm_high],
												prim.index[msm_high], primr.index[msm_high],
												sec.index[msm_high], secr.index[msm_high],
												early.index[msm_high], earlyr.index[msm_high],
												latent.index[msm_high], latentr.index[msm_high])]) 

		) %>% 
	mutate(msm_low = msm_low / popsize_low * 100, 
		msm_high = msm_high / popsize_high * 100
	) %>% 
	select(-popsize_low, -popsize_high) %>% 
	gather(risk, infections, -year) %>% 
	as.data.frame() 
}



for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_msm_prevalence_by_risk))
}

df6 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))

p11 <- ggplot(filter(df6, state == 'Louisiana'), aes(x = year, y = infections, color = risk)) + 
	geom_line(size=1.2) + 
	# scale_color_brewer(palette="Purples") + 
	ylab("Prevalent Infections") + 
	facet_wrap(~ intervention) + 
	xlab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Prevalence Rate in MSM Infections per 100 by Risk", subtitle = 'Louisiana') 

ggsave(plot = p11, filename = 'prevalence_msm_by_risk_la.png', width = unit(10, 'in'), height = unit(5, 'in'))


p12 <- ggplot(filter(df6, state == 'Massachusetts'), aes(x = year, y = infections, color = risk)) + 
	geom_line(size=1.2) + 
	# scale_color_brewer(palette="Purples") + 
	ylab("Prevalent Infections") + 
	facet_wrap(~ intervention) + 
	xlab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Prevalence Rate in MSM Infections per 100 by Risk", subtitle = 'Massachusetts') 



ggsave(plot = p12, filename = 'prevalence_msm_by_risk_ma.png', width = unit(10, 'in'), height = unit(5, 'in'))

```


```{r}

#' Breakdown Prevalence by Sex
#' Extract from a simulation matrix (sol) the diagnoses by stage, 
#' reshape the data into a year, stage, count column format. 
breakdown_prevalence_by_sex <- function(sol) { 
	intervention_start <- min(intervention_years)
	intervention_period <- seq((intervention_start-1)*52-1, model.end*52)

	data.frame(
		year = intervention_period/52 + model_to_gregorian_difference,
		popsize = rowSums(sol[intervention_period, allpop.index]),

		msm = rowSums(sol[intervention_period, 1 + 
													c(
														e.index[msm], er.index[msm],
														prim.index[msm], primr.index[msm],
														sec.index[msm], secr.index[msm],
														early.index[msm], earlyr.index[msm], 
														latent.index[msm], latentr.index[msm])]),

		msw = rowSums(sol[intervention_period, 1 + 
													c(
														e.index[msw], er.index[msw],
														prim.index[msw], primr.index[msw],
														sec.index[msw], secr.index[msw],
														early.index[msw], earlyr.index[msw], 
														latent.index[msw], latentr.index[msw])]),

		w = rowSums(sol[intervention_period, 1 + 
													c(
														e.index[females], er.index[females],
														prim.index[females], primr.index[females],
														sec.index[females], secr.index[females],
														early.index[females], earlyr.index[females], 
														latent.index[females], latentr.index[females])])

		) %>% 
	mutate(msw = msw / popsize * 100000, 
		msm = msm / popsize * 100000,
		w = w / popsize * 100000
	) %>% 
	select(-popsize) %>% 
	gather(sex, infections, -year) %>% 
	as.data.frame() 
}


for (state in c('LA', 'MA')) { 

	# set the number of years to run out the model to 2050
	load_globals(model.end = 116)

	# parametrize the model
	load.start()

	# get optimized for the model in the specified state.
	theta <- get(paste0('theta_', tolower(state)))



	# simmulate the annual and basecase scenarios getting
	# - prevalent cases, incidents, and number of tests done
	assign(paste0(tolower(state), '_df'),
				 simulate_interventions(theta, info_extractor = breakdown_prevalence_by_sex))
}

df7 <- rbind.data.frame(
	cbind.data.frame(state = 'Louisiana', la_df),
	cbind.data.frame(state = 'Massachusetts', ma_df))

p13 <- ggplot(filter(df7, state == 'Louisiana'), aes(x = year, y = infections, fill = sex)) + 
	geom_area(color = 'black', size=.2) + 
	scale_fill_brewer(palette="Purples") + 
	ylab("Prevalent Infections") + 
	facet_wrap(~ intervention) + 
	xlab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Prevalence Rate per 100,000 by Sex", subtitle = 'Louisiana') 

ggsave(plot = p13, filename = 'prevalence_by_sex_la.png', width = unit(10, 'in'), height = unit(5, 'in'))

p14 <- ggplot(filter(df7, state == 'Massachusetts'), aes(x = year, y = infections, fill = sex)) + 
	geom_area(color = 'black', size=.2) + 
	scale_fill_brewer(palette="Purples") + 
	ylab("Prevalent Infections") + 
	facet_wrap(~ intervention) + 
	xlab("Year") + 
	scale_x_continuous(breaks = seq(2016, 2027, by = 2)) + 
	theme(axis.text.x = element_text(angle = 90)) + 
	labs(fill = 'sex') + 
	ggtitle("Prevalence Rate per 100,000 by Sex", subtitle = 'Massachusetts') 

ggsave(plot = p14, filename = 'prevalence_by_sex_ma.png', width = unit(10, 'in'), height = unit(5, 'in'))


```

