# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_mult <- function(lhs, rhs) {
    .Call('_syphilis_mv_mult', PACKAGE = 'syphilis', lhs, rhs)
}

mat_mult <- function(a, b) {
    .Call('_syphilis_mat_mult', PACKAGE = 'syphilis', a, b)
}

syphSim <- function(x, dt, cm, pabx, rep_count, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa) {
    .Call('_syphilis_syphSim', PACKAGE = 'syphilis', x, dt, cm, pabx, rep_count, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa)
}

syphSimCTCounterfactual <- function(x, dt, cm, pabx, rep_count, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa) {
    .Call('_syphilis_syphSimCTCounterfactual', PACKAGE = 'syphilis', x, dt, cm, pabx, rep_count, nYrs, initPop, n_sa, births, births_sa, births_nsa, aging, aging_nsa)
}

